[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "IQA_Metrics_Toolbox"
version = "2023.0.1"
authors = [
  { name="Daniel Gummadi", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=1.19.1",
    "cycler>=0.11.0",
    "fonttools>=4.28.2",
    "imageio>=2.11.1",
    "kiwisolver>=1.3.2",
    "libsvm>=3.23.0.4",
    "matplotlib>=3.5.0",
    "networkx>=2.6.3",
    "opencv-python>=4.5.4.60",
    "packaging>=21.3",
    "Pillow>=9.2.0",
    "pyparsing>=3.0.6",
    "python-dateutil>=2.8.2",
    "PyWavelets>=1.2.0",
    "scikit-image>=0.18.3",
    "scipy>=1.7.2",
    "setuptools-scm>=6.3.2",
    "six>=1.16.0",
    "tifffile>=2021.11.2",
    "tomli>=1.2.2",
    "pandas>=1.5.1"
]
