[tool.poetry]
name = "issurge"
version = "0.1.0"
description = "Deal with your client's feedback efficiently by creating a bunch of issues in bulk from a text file."
authors = ["Ewen Le Bihan <hey@ewen.works>"]
readme = "README.md"
scripts = { issurge = "issurge.main:run" }

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.3.3"
docopt = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
