[project]
name = "api_selectel"
version = "0.1.1"
authors = [
  { name="Artem Gnatyuk", email="temskiy@gmail.com" },
]
description = "A selectel api package"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
  "Jinja2>=2.10",
  "requests>=2.18.4",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/temskiy/selectel_api"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
