[tool.poetry]
name = "faudantic"
version = "0.1.3"
description = ""
authors = ["Oscar Bahamonde <107950590+obahamonde@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
faunadb = "^4.5.0"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
aiohttp = "^3.8.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pytest = "pytest:main"