[build-system]
requires = [
    "setuptools>=61.0", 
]
build-backend = "setuptools.build_meta"
[project]
name = "flgo"
version = "0.0.4"
authors = [
  { name="Zheng Wang", email="zwang@stu.xmu.edu.cn" },
]
description = "A Research-oriented FL Platform. "
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/WwZzz/FLGo"
"Bug Tracker" = "https://github.com/WwZzz/FLGo/issues"
