[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "launchflow"
version = "0.1.2"
authors = [
    { name = "Caleb Van Dyke", email = "caleb@launchflow.com" },
    { name = "Josh Tanke", email = "josh@launchflow.com" },
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "fastapi",
    "google-auth",
    "pydantic",
    "pydata-google-auth",
    "pyaml",
    "requests",
    "ray",
    "typer[all]",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
]

[project.optional-dependencies]
dev = [
    "httpx",
    "pytest",
    "flake8",
    "requests-mock",
    "setuptools",
    "wheel"
]

[project.scripts]
launch = "launch.cli:main"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[tool.setuptools]
py-modules = ["custom_cmds"]

[tool.setuptools.cmdclass]
build_py = "custom_cmds.InstallCustomDeps"

[tool.setuptools.package-data]
launch = ['prometheus/prometheus', 'prometheus/prometheus.yml']
