[build-system]
requires = ["hatchling", "requests"]
build-backend = "hatchling.build"

[project]
name = "okxpy"
version = "0.1.7"
authors = [
  { name="Enkh-Amar Ganbat", email="amra.developer@gmail.com" },
]
description = "A pip package for a Python wrapper that provides an interface to the OKX API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'requests',
]

[project.urls]
"Homepage" = "https://github.com/EnkhAmar/okxpy"
"Bug Tracker" = "https://github.com/EnkhAmar/okxpy/issues"