[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[project]
name = "tabs-settings"
version = "0.1.0"
description = "Handle all settings for tabs. Includes data download and storage."
authors = [
    { name = "Alexis Rosuel", email = "rosuelalexis1@gmail.com" },
]
dependencies = [
    "numpy>=1.24.2",
    "immutables>=0.19",
    "pandas>=1.5.3",
    "scikit-optimize>=0.9.0",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
exclude = [
    "tests",
]
namespaces = true

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
addopts = "--cov=tabs_settings"

[tool.coverage.run]
omit = [
    "*/.local/*",
    "__init__.py",
    "tests/*",
    "*/tests/*",
    ".venv/*",
]

[tool.coverage.report]
skip_empty = true

[tool.black]
line-length = 88
target-version = [
    "py39",
]
include = "\\.pyi?$"
preview = true

[tool.flake8]
per-file-ignores = [
    "__init__.py:F401",
]
max-line-length = 88
count = true

[tool.isort]
py_version = 39
known_third_party = []
known_first_party = [
    "",
]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.2",
    "pytest-cov>=4.0.0",
]
