[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[project]
name = "tabs-storage"
version = "0.1.0"
description = "Handle the where and how of the storage logic"
authors = [
    { name = "Alexis Rosuel", email = "rosuelalexis1@gmail.com" },
]
dependencies = [
    "ujson>=5.7.0",
    "xarray>=2023.2.0",
    "hdf5plugin>=4.1.1",
    "pyyaml>=6.0",
    "zstandard>=0.20.0",
    "h5netcdf>=1.1.0",
    "polars>=0.16.13",
    "pyarrow>=11.0.0",
    "tabs-settings>=0.1.0",
    "tabs-type>=0.1.0",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
exclude = [
    "tests",
]
namespaces = true

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
addopts = "--cov=tabs_storage"

[tool.coverage.run]
omit = [
    "*/.local/*",
    "__init__.py",
    "tests/*",
    "*/tests/*",
    ".venv/*",
]

[tool.coverage.report]
skip_empty = true

[tool.black]
line-length = 88
target-version = [
    "py39",
]
include = "\\.pyi?$"
preview = true

[tool.flake8]
per-file-ignores = [
    "__init__.py:F401",
]
max-line-length = 88
count = true

[tool.isort]
py_version = 311
known_third_party = []
known_first_party = [
    "tabs-storage",
]

[tool.pdm.version]
source = "scm"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.2",
    "pytest-cov>=4.0.0",
]
