[project]
name = "telegram-botty"
version = "0.3.14"
description = ""
authors = [
    { name = "levch", email = "levchenko.d.a1998@gmail.com" },
]
dependencies = [
    "python-telegram-bot>=20.1",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
dev = [
    "stricter>=0.1.3",
]

[tool.pdm.scripts]
lint = "python -m stricter"

[tool.pdm.scripts.test]
cmd = "python tests"
env_file = ".env"

[tool.pdm.scripts.dev]
composite = [
    "lint",
    "test",
]

[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff]
src = [
    "botty",
    "botty_core",
    "tests",
]

[tool.isort]
profile = "black"
