[tool.poetry]
name = "bng-data"
version = "0.1.5"
description = ""
authors = ["Brian Mitchell <bmitchell@beeldengeluid.nl>"]
readme = "README.md"
packages = [{include = "bng_data"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
elasticsearch = "^8.6.2"
elasticsearch5 = "^5.5.6"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
